config/routes.rb
Rails.application.routes.draw do
  
  root 'home#index'
  get 'index', to: 'home#index', as: 'index'
  get 'write', to: 'home#write'
  get 'update/:post_id', to: 'home#update', as: 'update'
  get 'destroy/:post_id', to: 'home#destroy', as:'destroy'
  post 'result', to: 'home#result'
  post 'update_result/:post_id', to: 'home#update_result'

end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @every_post = Post.all.order("id desc")
  end

  def write
  end

  def update
    @update_post = Post.find(params[:post_id])
  end
  
  def update_result
    @title = params[:title]
    @content = params[:content]
    @update_post = Post.find(params[:post_id])
    @update_post.title = @title
    @update_post.content = @content
    @update_post.save
  end

  def destroy
    @destroy_post = Post.find(params[:post_id])
    @destroy_post.delete
  end
  
  def result
    @title = params[:title]
    @content = params[:content]
    @save_post = Post.new
    @save_post.title = @title
    @save_post.content = @content
    @save_post.save
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/destroy.html.erb
<h1>삭제가 되었습니다.</h1>

<br><%= link_to index_path do %>  <!-- <%= link_to "텍스트", "URL" %> -->
    <button>메인으로 가기</button>
<% end %>

app/views/home/index.html.erb
<a href ="/write">
    <button>글쓰러 가보겠습니다.;</button>
</a><br>

<% @every_post.each do |p| %>
    <br>게시글번호 : <%= p.id %>
    <br>제목 : <%= p.title %>
    <br>내용  : <%= p.content %>
    <br>등록일 : <%= p.created_at %>
    <br><%=link_to "[삭제]", destroy_path(p) %>
    <%=link_to "[수정]", update_path(p) %>
    <hr>
<% end %>

app/views/home/result.erb
<p>제목: <%= @title %></p>
<p>내용: <%= @content %></p>

<br><%= link_to index_path do %>  <!--<%= link_to "텍스트", "URL" %>-->
    <button>메인으로 가기</button>
<% end %>

app/views/home/update.html.erb
<h1>여기는 수정하는 곳입니다.</h1>

<form action="/update_result/<%= @update_post.id %>" method="POST">  
    <br>제목 : <input type="text" name="title" value="<%= @update_post.title %>">
    <br>내용 : <input type="text" name="content" value="<%= @update_post.content %>">
    <br><br><input type="submit" value="수정하기">
</form>

app/views/home/update_result.erb
<h1>수정이 완료되었습니다.</h1>

<p>수정된 제목: <%= @title %></p>
<p>수정된내용: <%= @content %></p>

<br><%= link_to index_path do %>  
    <button>메인으로 가기</button>
<% end %>

app/views/home/write.html.erb
<h1>여기는 글쓰는 곳입니다.</h1>

<form action="result" method="POST">  <!-- 글이 길어지면 POST이용-->
    <br>제목 : <input type="text" name="title">
    <br>내용 : <input type="text" name="content">
    <br><br><input type="submit" value="글쓰기"> <!--버튼 넣어주기 value로 버튼 이름지정-->
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>